#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH=$HOME/.bin:$PATH

if [ -d "/opt/boxen/homebrew/bin"  ]; then
  export PATH=/opt/boxen/homebrew/bin:$PATH
fi

## Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
